import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-headers/main-header"
const inter = Inter({ subsets: ["latin"] });
import ManinHeaderBackground from "@/components/main-headers/main-header-background";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
    <ManinHeaderBackground/>
        <MainHeader/>
        {children}</body>
    </html>
  );
}
